import { Icon } from '../../components/Icon';
import { FavoriteButton } from '../carta/FavoriteButton';
import { products, soles } from '../carta/catalog';
import type { useCarta } from '../carta/useCarta';

export function CartProducts({ cart, onBrowse }: { cart: ReturnType<typeof useCarta>; onBrowse: () => void }) {
  return <section className="checkout-panel cart-products" aria-labelledby="cart-products-title"><div className="checkout-panel-heading"><h2 id="cart-products-title"><Icon name="cart" />Productos en tu carrito ({cart.count})</h2>{cart.count > 0 && <button className="checkout-text-button" type="button" onClick={cart.clearCart}><Icon name="trash" />Vaciar carrito</button>}</div>
    {cart.cartItems.length ? <ul className="cart-product-list">{cart.cartItems.map(({ product, count }) => <li key={product.id}><img src={product.image} alt={product.name} width="220" height="150" /><div className="cart-product-copy"><h3>{product.name}</h3><p>{product.description}</p></div><div className="cart-unit-price"><strong>{soles(product.price)}</strong><small>Precio unitario</small></div><div className="checkout-quantity" role="group" aria-label={`Cantidad de ${product.name}`}><button type="button" disabled={count <= 1} aria-label={`Quitar una unidad de ${product.name}`} onClick={() => cart.quantity(product.id, -1)}>−</button><output>{count}</output><button type="button" disabled={count >= 99} aria-label={`Agregar una unidad de ${product.name}`} onClick={() => cart.quantity(product.id, 1)}>+</button></div><div className="cart-row-actions"><FavoriteButton selected={cart.favorites.includes(product.id)} productName={product.name} onToggle={() => cart.favorite(product.id)} /><button type="button" aria-label={`Eliminar ${product.name}`} onClick={() => cart.remove(product.id)}><Icon name="trash" /></button></div></li>)}</ul> : <div className="checkout-empty"><Icon name="cart" /><h3>Tu carrito está esperando algo rico</h3><p>Encuentra tu próximo antojo en nuestra carta.</p><button className="primary-button" type="button" onClick={onBrowse}>Ver carta <Icon name="arrow" /></button></div>}
  </section>;
}
export function CartRecommendations({ onAdd, onBrowse }: { onAdd: (id: string) => void; onBrowse: () => void }) {
  const suggestions = ['acompanamientos-03', 'acompanamientos-06', 'salsas-01'].map(id => products.find(product => product.id === id)).filter(product => product !== undefined);
  return <section className="cart-recommendations" aria-labelledby="recommendations-title"><div className="checkout-panel-heading"><h2 id="recommendations-title"><Icon name="flame" />Añade algo más</h2><button className="checkout-text-button" type="button" onClick={onBrowse}>Ver más productos <Icon name="arrow" /></button></div><div>{suggestions.map(product => <article key={product.id}><img src={product.image} alt={product.name} width="160" height="120" /><div><h3>{product.name}</h3><p>{product.description}</p><strong>{soles(product.price)}</strong><button className="checkout-outline" type="button" onClick={() => onAdd(product.id)} aria-label={`Agregar ${product.name}`}>+ Agregar</button></div></article>)}</div></section>;
}
