import { Icon } from '../../components/Icon';
import { OrderItems, OrderTotals } from './OrderSummary';
import { paymentNames, type CartItem, type Checkout, type Receipt } from './useCheckout';

export function ConfirmationStep({ checkout, items, onEdit }: { checkout: Checkout; items: CartItem[]; onEdit: (step: 'delivery' | 'payment') => void }) {
  const { delivery } = checkout;
  return <div className="checkout-confirmation"><div className="checkout-section-heading"><div><h1>Confirmación de pedido</h1><p>Revisa que toda la información sea correcta antes de finalizar tu pedido.</p></div></div><section className="checkout-panel"><div className="checkout-panel-heading"><h2>1. Revisa tu información</h2><button className="checkout-text-button" type="button" onClick={() => onEdit('delivery')}>Editar</button></div><div className="checkout-review-grid"><div><Icon name="pin" /><h3>Dirección y entrega</h3><strong>{delivery.mode === 'delivery' ? delivery.address : delivery.store}</strong><p>{delivery.mode === 'delivery' ? delivery.district : 'Recojo en local'}</p><p>Referencia: {delivery.reference || 'No aplica'}</p><div className="checkout-review-delivery"><Icon name="truck" />{delivery.mode === 'delivery' ? 'Delivery' : 'Recojo'} · 25 – 35 min</div></div><div><Icon name="card" /><h3>Método de pago</h3><strong>{paymentNames[checkout.method]}</strong><p>{checkout.method === 'cash' ? 'Pago al recibir' : 'Pago simulado, sin cobro real'}</p><button className="checkout-text-button" type="button" onClick={() => onEdit('payment')}>Cambiar método</button></div><div><Icon name="receipt" /><h3>Datos adicionales</h3><strong>Notas del pedido</strong><p>{delivery.instructions || 'Sin instrucciones adicionales'}</p><strong>Número de contacto</strong><p>{delivery.phone}</p><strong>{delivery.name}</strong><p>{delivery.email}</p></div></div></section><section className="checkout-panel"><h2>2. Revisa tu pedido</h2><OrderItems items={items} /></section></div>;
}
export function OrderResult({ receipt, tracking, onHome, onTrack }: { receipt: Receipt; tracking: boolean; onHome: () => void; onTrack: () => void }) {
  const date = new Date(receipt.date);
  return <div className="checkout-result"><div className="checkout-result-heading"><svg className="checkout-confetti" viewBox="0 0 800 180" aria-hidden="true"><g fill="#ef0008"><path d="m135 40 12 8-5 10-12-8zm68 65 10-4 5 15-10 4zm-75 35 8 3-4 15-8-3zm480-84 13-8 5 8-13 8zm67 64 8 4-7 15-8-4z" /></g><g fill="#efa035"><path d="m225 23 13 7-5 8-13-7zm-10 115 8 4-5 13-8-4zm395-6 10 3-4 14-10-3zm-80-87 12-6 4 9-12 6zm-238-33 7 6-10 11-7-6z" /></g></svg><span className="checkout-success-icon"><Icon name="check" /></span><h1>{tracking ? 'Tu pedido de demostración' : '¡Pedido confirmado!'}</h1><p>{tracking ? 'Estos son los detalles de tu selección.' : 'Tu pedido de demostración se registró con éxito. Puedes revisar todos los detalles aquí.'}</p><small>No se realizó ningún cobro ni se envió un pedido al local.</small></div><div className="checkout-layout"><section className="checkout-panel"><div className="checkout-order-code"><Icon name="receipt" /><div><span>Código de pedido</span><strong>#{receipt.code}</strong></div><div><span>Fecha y hora</span><b>{date.toLocaleDateString('es-PE', { day: 'numeric', month: 'short', year: 'numeric' })}</b><small>{date.toLocaleTimeString('es-PE', { hour: '2-digit', minute: '2-digit' })}</small></div></div><dl className="checkout-order-details"><div><dt><Icon name="clock" />Tiempo estimado</dt><dd><strong>25 – 35 minutos</strong><small>Estimación visual de demostración</small></dd></div><div><dt><Icon name="pin" />{receipt.delivery.mode === 'delivery' ? 'Dirección de entrega' : 'Recojo en local'}</dt><dd><strong>{receipt.delivery.mode === 'delivery' ? receipt.delivery.address : receipt.delivery.store}</strong><p>{receipt.delivery.district}</p><small>Referencia: {receipt.delivery.reference || 'No aplica'}</small></dd></div><div><dt><Icon name="card" />Método de pago</dt><dd><strong>{paymentNames[receipt.method]}</strong><span className="checkout-payment-status">{receipt.method === 'cash' ? 'Pendiente de cobro (demo)' : 'Pago simulado'}</span></dd></div><div><dt><Icon name="user" />Datos de contacto</dt><dd><strong>{receipt.delivery.name}</strong><small>{receipt.delivery.phone} · {receipt.delivery.email}</small></dd></div></dl>{tracking && <p className="checkout-payment-note">Estado: registrado en esta demostración. El seguimiento en tiempo real se habilitará al conectar pedidos.</p>}</section><aside className="checkout-panel"><div className="checkout-panel-heading"><h2>Resumen de tu pedido</h2><span>{receipt.items.length} productos</span></div><OrderItems items={receipt.items} /><OrderTotals {...receipt} final /></aside></div><div className="checkout-result-actions">{!tracking && <button type="button" className="primary-button" onClick={onTrack}>Ver mi pedido <Icon name="arrow" /></button>}<button type="button" className="checkout-outline" onClick={onHome}><Icon name="home" />Volver al inicio</button></div></div>;
}
