import { useEffect, useRef, useState } from 'react';
import { AddressAutocomplete } from './AddressAutocomplete';
import { DistrictSelect } from './DistrictSelect';
import { DeliveryMap } from './DeliveryMap';
import type { DeliveryPoint } from './location';
import { Icon } from '../../components/Icon';
import type { DeliveryDraft } from './useCheckout';

type Address = { label: string; address: string; district: string; location?: DeliveryPoint | null };
export function DeliveryStep({ value, onChange, onContinue }: { value: DeliveryDraft; onChange: (value: DeliveryDraft) => void; onContinue: () => void }) {
  const [addresses, setAddresses] = useState<Address[]>(() => value.address ? [{ label: value.label, address: value.address, district: value.district, location: value.location }] : []);
  const [addressDraft, setAddressDraft] = useState<Address>({ label: 'Casa', address: '', district: '' });
  const [editing, setEditing] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { if (editing) dialog.current?.showModal(); else dialog.current?.close(); }, [editing]);
  function patch(key: keyof DeliveryDraft, content: string) { onChange({ ...value, [key]: content, ...(['address', 'district'].includes(key) ? { location: null } : {}) }); }
  function edit(label = 'Casa') { setAddressDraft({ label, address: value.label === label ? value.address : '', district: value.label === label ? value.district : '', location: value.label === label ? value.location : null }); setEditing(true); }
  return <section className="checkout-panel delivery-step"><div className="checkout-section-heading"><Icon name="pin" /><div><h1>Dirección y entrega</h1><p>Indica cómo y dónde quieres recibir tu pedido</p></div></div>
    <form id="delivery-form" onSubmit={event => { event.preventDefault(); onContinue(); }}>
      <fieldset><legend>Tipo de entrega</legend><div className="checkout-choice-grid">{[{ id: 'delivery', name: 'Delivery', description: 'Recibe tu pedido en la comodidad de tu casa u oficina.', icon: 'truck' as const }, { id: 'pickup', name: 'Recojo en local', description: 'Haz tu pedido y recógelo en nuestro local.', icon: 'store' as const }].map(option => <label key={option.id} className="checkout-choice" data-selected={value.mode === option.id}><Icon name={option.icon} /><span><strong>{option.name}</strong><small>{option.description}</small></span><input type="radio" name="delivery-mode" value={option.id} checked={value.mode === option.id} onChange={() => onChange({ ...value, mode: option.id as DeliveryDraft['mode'] })} /></label>)}</div></fieldset>
      {value.mode === 'delivery' ? <><h2 className="checkout-field-heading">Selecciona una dirección</h2><div className="checkout-addresses">{['Casa', 'Trabajo'].map(label => {
        const address = addresses.find(item => item.label === label);
        return <button type="button" key={label} className="checkout-choice" data-selected={value.label === label && !!value.address} onClick={() => address ? onChange({ ...value, ...address, location: address.location || null }) : edit(label)}><Icon name={label === 'Casa' ? 'home' : 'store'} /><span><strong>{label}</strong><small>{address ? `${address.address}, ${address.district}` : 'Agregar tu dirección'}</small></span><span className="address-radio" aria-hidden="true" /></button>;
      })}{addresses.filter(item => !['Casa', 'Trabajo'].includes(item.label)).map(address => <button type="button" key={address.label} className="checkout-choice" data-selected={value.label === address.label} onClick={() => onChange({ ...value, ...address, location: address.location || null })}><Icon name="pin" /><span><strong>{address.label}</strong><small>{address.address}</small></span></button>)}<button className="checkout-address-add" type="button" onClick={() => edit('Otra dirección')}>+ Agregar nueva dirección</button></div>
        <div className="checkout-field-grid"><AddressAutocomplete key={value.district} label="Dirección de entrega" value={value.address} district={value.district} onChange={address => patch('address', address)} onSelect={result => onChange({ ...value, address: result.title, location: result.point })} /><DistrictSelect value={value.district} onChange={district => patch('district', district)} /><label>Referencia <span>*</span><input required minLength={3} maxLength={160} value={value.reference} placeholder="Frente al parque, casa color blanco" onChange={event => patch('reference', event.target.value)} /></label><label>Instrucciones de entrega (opcional)<input value={value.instructions} maxLength={300} placeholder="Ej. tocar la puerta, llamar antes…" onChange={event => patch('instructions', event.target.value)} /></label></div>
      </> : <label className="checkout-store-field">Selecciona el local<select value={value.store} onChange={event => patch('store', event.target.value)}><option>Local principal</option></select><small>La dirección y los horarios del local se configurarán al conectar pedidos.</small></label>}
      <h2 className="checkout-field-heading">Datos de contacto</h2><div className="checkout-field-grid"><label>Nombre completo <span>*</span><input autoComplete="name" required minLength={3} maxLength={100} value={value.name} onChange={event => patch('name', event.target.value)} placeholder="Nombre y apellidos" /></label><label>Celular <span>*</span><input type="tel" autoComplete="tel-national" required pattern="9[0-9]{8}" maxLength={9} inputMode="numeric" value={value.phone} onChange={event => patch('phone', event.target.value.replace(/\D/g, ''))} placeholder="987654321" /></label><label>Correo electrónico <span>*</span><input type="email" autoComplete="email" required maxLength={120} value={value.email} onChange={event => patch('email', event.target.value)} placeholder="tu@correo.com" /></label>{value.mode === 'pickup' && <label>Notas del pedido (opcional)<input maxLength={300} value={value.instructions} onChange={event => patch('instructions', event.target.value)} /></label>}</div>
      <div className="checkout-estimate"><Icon name="clock" /><div><span>Tiempo estimado de {value.mode === 'delivery' ? 'entrega' : 'preparación'}</span><strong>25 – 35 minutos</strong><small>Estimación de demostración</small></div><Icon name="truck" /><p>Tu pedido será preparado al momento</p></div>
      {value.mode === 'delivery' && <DeliveryMap point={value.location} onChange={location => onChange({ ...value, location })} />}
    </form>
    <dialog ref={dialog} className="checkout-address-dialog" onClose={() => setEditing(false)} aria-labelledby="address-dialog-title"><button type="button" className="dialog-close" aria-label="Cerrar dirección" onClick={() => setEditing(false)}><Icon name="close" /></button><h2 id="address-dialog-title">Agregar dirección</h2><form onSubmit={event => { event.preventDefault(); setAddresses(previous => [...previous.filter(item => item.label !== addressDraft.label), addressDraft]); onChange({ ...value, ...addressDraft }); setEditing(false); }}><label>Nombre de la dirección<input required maxLength={40} value={addressDraft.label} onChange={event => setAddressDraft({ ...addressDraft, label: event.target.value })} /></label><AddressAutocomplete key={addressDraft.district} label="Calle y número" value={addressDraft.address} district={addressDraft.district} onChange={address => setAddressDraft({ ...addressDraft, address, location: null })} onSelect={result => setAddressDraft({ ...addressDraft, address: result.title, location: result.point })} /><DistrictSelect value={addressDraft.district} onChange={district => setAddressDraft({ ...addressDraft, district, location: null })} /><button type="submit" className="primary-button">Guardar dirección</button></form></dialog>
  </section>;
}
