import { Icon } from '../../components/Icon';
import { useAccount } from './accountStore';
import { accountOrders } from './orders';
import { paymentNames, type PaymentMethod } from '../checkout/useCheckout';
import { OrderList } from './OrderList';
export function AccountDashboard({ favorites, onNavigate }: { favorites: number; onNavigate: (path: string) => void }) {
  const account = useAccount();
  const address = account.addresses.find(item => item.primary) || account.addresses[0];
  const stats = [{ value: accountOrders().length, label: 'Pedidos registrados', icon: 'cart', route: 'pedidos' }, { value: favorites, label: 'Productos favoritos', icon: 'heart', route: 'favoritos' }, { value: account.addresses.length, label: 'Direcciones guardadas', icon: 'pin', route: 'direcciones' }, { value: account.preferredPayment ? 1 : 0, label: 'Preferencia de pago', icon: 'card', route: 'metodos-pago' }] as const;
  return <div className="account-dashboard"><div className="account-dashboard-main"><section className="info-card account-welcome"><span className="info-icon-circle"><Icon name="user" /></span><div><h2>¡Hola{account.profile.name ? `, ${account.profile.name.split(' ')[0]}` : ''}!</h2><p>Bienvenido a Leñas y Sabores</p></div><button type="button" className="info-button" onClick={() => onNavigate('/mi-cuenta/datos')}>Editar perfil</button></section><div className="account-stats">{stats.map(stat => <button type="button" className="info-card" key={stat.label} onClick={() => onNavigate(`/mi-cuenta/${stat.route}`)}><span className="info-icon-circle"><Icon name={stat.icon} /></span><strong>{stat.value}</strong><span>{stat.label}</span></button>)}</div><OrderList compact onNavigate={onNavigate} /></div><aside className="account-dashboard-side"><section className="info-card"><div className="account-row-heading"><h2><Icon name="pin" />Dirección principal</h2><button className="account-text-button" type="button" onClick={() => onNavigate('/mi-cuenta/direcciones')}>{address ? 'Editar' : 'Agregar'}</button></div>{address ? <div className="account-dashboard-detail"><Icon name="home" /><div><strong>{address.street}</strong><p>{address.district}, Lima</p></div></div> : <p>Guarda una dirección para preparar tus pedidos más rápido.</p>}</section><section className="info-card"><div className="account-row-heading"><h2><Icon name="card" />Método de pago</h2><button className="account-text-button" type="button" onClick={() => onNavigate('/mi-cuenta/metodos-pago')}>Elegir</button></div><div className="account-dashboard-detail"><Icon name="card" /><div><strong>{account.preferredPayment ? paymentNames[account.preferredPayment as PaymentMethod] : 'Sin preferencia guardada'}</strong><p>Selecciona tu método al realizar el pedido.</p></div></div></section><section className="account-fast"><img src="/images/information/account-phone.webp" width="600" height="600" alt="" loading="lazy" /><div><h3>¡Haz tu pedido <span>más rápido!</span></h3><p>Guarda tus direcciones y elige tus favoritos.</p></div></section></aside></div>;
}
