import { useOperations } from '../operations/operationsStore';
import { useState } from 'react';
import { Icon, type IconName } from '../../components/Icon';
import { accountOrders } from './orders';
import { updateAccount, useAccount } from './accountStore';
import { AccountEmpty } from './AccountShared';
type Notification = { id: string; category: string; title: string; message: string; icon: IconName; route: string; example?: boolean };
const samples: Notification[] = [
  { id: 'example-delivered', category: 'Pedidos', title: 'Tu pedido ha sido entregado', message: '¡Gracias por compartir un buen momento con nosotros!', icon: 'cart', route: '/mi-cuenta/pedidos', example: true },
  { id: 'example-delivery', category: 'Pedidos', title: 'Tu pedido está en camino', message: 'Tu pedido salió del local y está en ruta de entrega.', icon: 'truck', route: '/mi-cuenta/pedidos', example: true },
  { id: 'example-promo', category: 'Promociones', title: 'Descubre nuestras promociones', message: 'Encuentra tu próximo favorito para compartir en familia.', icon: 'tag', route: '/promociones', example: true },
  { id: 'example-favorite', category: 'Promociones', title: 'Tus productos favoritos te esperan', message: 'Agrega tus favoritos al pedido en pocos pasos.', icon: 'heart', route: '/mi-cuenta/favoritos', example: true },
  { id: 'example-profile', category: 'Cuenta', title: 'Mantén tu información actualizada', message: 'Guarda tus datos y direcciones para preparar tu siguiente pedido.', icon: 'user', route: '/mi-cuenta/datos', example: true },
];
const preferences = [{ key: 'orders', label: 'Estado de pedidos', description: 'Cambios en el estado de tus pedidos.', icon: 'truck' }, { key: 'promotions', label: 'Promociones y ofertas', description: 'Novedades y descuentos exclusivos.', icon: 'tag' }, { key: 'favorites', label: 'Productos favoritos', description: 'Alertas sobre productos de tu lista.', icon: 'heart' }, { key: 'account', label: 'Novedades de la cuenta', description: 'Cambios en tus datos y seguridad.', icon: 'user' }] as const;
export function AccountNotifications({ onNavigate }: { onNavigate: (path: string) => void }) {
  useOperations();
  const account = useAccount();
  const [filter, setFilter] = useState('Todas');
  const [examples, setExamples] = useState(false);
  const notifications: Notification[] = examples ? samples : accountOrders().map(order => ({ id: order.code+order.status, category: 'Pedidos', title: `Pedido #${order.code} · ${order.status}`, message: 'Consulta el estado actualizado en Mis pedidos.', icon: 'receipt', route: '/mi-cuenta/pedidos' }));
  return <><div className="account-filter-tabs" aria-label="Filtrar notificaciones">{['Todas', 'Pedidos', 'Promociones', 'Cuenta'].map(category => <button type="button" aria-pressed={filter === category} key={category} onClick={() => setFilter(category)}>{category} ({notifications.filter(item => category === 'Todas' || item.category === category).length})</button>)}</div><div className="account-actions-heading"><label className="account-example-switch"><input type="checkbox" checked={examples} onChange={event => setExamples(event.target.checked)} />Ver notificaciones de ejemplo</label><button type="button" className="account-text-button" onClick={() => updateAccount({ readNotifications: [...new Set([...account.readNotifications, ...notifications.map(item => item.id)])] })}>Marcar todas como leídas</button></div>{!notifications.filter(item => filter === 'Todas' || item.category === filter).length && <AccountEmpty title="Estás al día" description="Aquí podrás consultar las novedades de tus pedidos de demostración." />}{notifications.filter(item => filter === 'Todas' || item.category === filter).map(item => <button className="info-card account-notification" type="button" key={item.id} onClick={() => { updateAccount({ readNotifications: [...new Set([...account.readNotifications, item.id])] }); onNavigate(item.route); }}><span className={account.readNotifications.includes(item.id) ? 'notification-dot read' : 'notification-dot'} aria-label={account.readNotifications.includes(item.id) ? 'Leída' : 'Sin leer'} /><span className="info-icon-circle"><Icon name={item.icon} /></span><span><strong>{item.title}</strong><small>{item.message}</small>{item.example && <small>Ejemplo de la interfaz</small>}</span><Icon name="arrow" /></button>)}<section className="info-card account-notification-settings"><h2>Configuración de notificaciones</h2><p>Elige qué comunicaciones deseas recibir. Preferencias de demostración; todavía no se envían avisos.</p>{preferences.map(preference => <div key={preference.key}><Icon name={preference.icon} /><span><strong>{preference.label}</strong><small>{preference.description}</small></span><button type="button" className="account-switch" role="switch" aria-checked={account.preferences[preference.key]} aria-label={preference.label} onClick={() => updateAccount({ preferences: { ...account.preferences, [preference.key]: !account.preferences[preference.key] } })}><span /></button></div>)}</section></>;
}
