import { Icon, type IconName } from '../components/Icon';
import { PageHero, InformationNavigation } from '../features/information/InformationShared';
const milestones: { title: string; description: string; image: string; icon: IconName }[] = [
  { title: 'El inicio en Carabayllo', description: 'Todo comenzó en nuestro barrio, con un gran sueño familiar.', image: '/images/carta/products/pollo-01.webp', icon: 'home' },
  { title: 'La receta familiar', description: 'Sabores que pasan de generación en generación.', image: '/images/carta/products/salsas-01.webp', icon: 'bowl' },
  { title: 'Un punto de encuentro', description: 'Un lugar donde las familias y amigos siempre se reúnen.', image: '/images/carta/products/combos-01.webp', icon: 'users' },
  { title: 'Seguimos creciendo', description: 'Con la misma pasión, llevando nuestro sabor cada vez más lejos.', image: '/images/carta/products/parrillas-01.webp', icon: 'flame' },
];
export function AboutPage({ onAction }: { onAction: (action: string) => void }) {
  return <><main id="contenido" className="information-page"><div className="info-container"><PageHero eyebrow="Nuestra historia" title="Una historia que comenzó en" accent="Carabayllo" description="El sabor de nuestra leña, el calor de nuestro barrio y un buen motivo para reunirnos." /><section className="about-story"><div><h2>De nuestra familia a tu mesa</h2><p>Leñas y Sabores nació en Carabayllo, de una tradición familiar y del inconfundible aroma del pollo a la leña que une a las personas.</p><p>Con recetas heredadas de generación en generación y el calor de nuestro barrio, creamos un lugar donde las familias y amigos siempre encuentran un buen motivo para reunirse.</p><button type="button" className="primary-button" onClick={() => onAction('Carta')}>Conoce nuestra carta <Icon name="arrow" /></button></div><img src="/images/home/hero-tradicion-1080.webp" width="1080" height="608" alt="Pollo a la brasa con papas, preparado para compartir" /></section><ol className="about-timeline">{milestones.map((item, index) => <li key={item.title}><div className="about-milestone-image"><img src={item.image} alt="" loading="lazy" /><span>{index + 1}</span></div><div><h3>{item.title}</h3><p>{item.description}</p></div></li>)}</ol><section className="about-essence"><p className="info-eyebrow">Nuestra esencia</p><h2>Lo que nos guía <span>cada día</span></h2><p>Nuestra misión, visión y valores reflejan el compromiso con Carabayllo, nuestras familias y el auténtico sabor a la brasa.</p><div className="about-values"><article className="info-card"><span className="info-icon-circle"><Icon name="cutlery" /></span><h3>Misión</h3><p>Brindar una experiencia gastronómica cálida, con auténtico sabor a la brasa, ingredientes de calidad y un servicio cercano para cada familia.</p></article><article className="info-card"><span className="info-icon-circle"><Icon name="eye" /></span><h3>Visión</h3><p>Ser una pollería referente en Carabayllo y Lima Norte, reconocida por su sabor, calidad y cercanía.</p></article><article className="info-card"><span className="info-icon-circle"><Icon name="heart" /></span><h3>Valores</h3><ul>{['Calidad', 'Compromiso', 'Trabajo en equipo', 'Pasión por servir'].map(value => <li key={value}><Icon name="check" />{value}</li>)}</ul></article></div></section></div></main><InformationNavigation active="Nosotros" onAction={onAction} /></>;
}
